print("Как Вас зовут?")
name = input()
print("Как Ваше отчество?")
lastname = input()
print("Как Ваша фамилия?")
surname = input()
print('Здравствуйте, ' + name + ' ' + lastname + ' ' + surname + ' ' + '-' + ' человек и пароход')